name: ShellCheck

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install ShellCheck
      run: |
        sudo apt-get update -qy
        sudo apt-get install shellcheck -y
      shell: bash
    - name: Run ShellCheck
      run: shellcheck ./*.sh
